### ISSUE TITLE
Layout Issues Firefox Mobile Devices

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/Geoguess#104] opened 2021-02-09 18:27 UTC
### Smartphone view

- Device: Oneplus Nord
- Android 10
- Device resolution: 1.080 x 2.400
- Browser: Firefox 85.1.2
- Problem: Map not viewable, does not open when clicking on bottom space

https://user-images.githubusercontent.com/25705332/107408423-3e5c9800-6b0b-11eb-815d-d583d5a1ec32.mp4

### Tablet view

- Device: Samsung Galaxy Tab S6
- Android 10
- Device resolution: 2560 x 1600
- Browser: Firefox 85.1.2
- Problem: The Button "Guess" is not clickable. The Marker will set itself "under" the button onto the map.

https://user-images.githubusercontent.com/25705332/107409713-c1322280-6b0c-11eb-8d3c-446db52921ed.mp4

**Comment by BilelJegham** [comment] 2021-02-11 20:02
I can't reproduce the bug on https://deploy-preview-103--geoguess2.netlify.app/
I think it's linked to developpement environnement.

Can you test again with https://deploy-preview-103--geoguess2.netlify.app/ ?

https://user-images.githubusercontent.com/20130405/107691727-1c4e4b80-6cac-11eb-889d-fde62eebaee6.mp4

**Comment by wlanowski** [comment] 2021-02-11 20:28
Unfortunately no success. I have the same issues. Of course, I cleaned the cache and cookies before testing.

Note: If I try it via the dev options in Firefox Desktop (set responsive design on and set resolution of the tablet), there is no problem. On the native device with firefox app, the problem occurs :(

**Comment by wlanowski** [comment] 2021-02-12 08:51
I asked a friend to test it on safari and iPhone. It looks brilliant there! 👍 Just for motivation! :)

**Comment by BilelJegham** [comment] 2021-02-13 00:03
I think it's fixed in https://deploy-preview-103--geoguess2.netlify.app/

Firefox doesn't like `height: 100%`

**Comment by wlanowski** [comment] 2021-02-13 00:58
I hate to say it, but there is no improvement for me :(

Did you tell me the right link?


https://user-images.githubusercontent.com/25705332/107836881-f48be000-6d9e-11eb-93d8-60a3f29932dd.mp4

https://user-images.githubusercontent.com/25705332/107836884-fa81c100-6d9e-11eb-83f0-9eec6c754f8d.mp4

**Closed** 2021-02-17 17:43 UTC
Labels: bug

**Comment by BilelJegham** [comment] 2021-02-17 17:48
I can't reproduce it, use chrome or build an apk (TWA) with https://www.pwabuilder.com/ (i will write a documentation soon)
![image](https://user-images.githubusercontent.com/20130405/108245403-87869a80-7150-11eb-85e1-825978d749e1.png)
